a=input('digite algo:')

print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços', a.isspace())
print('É um numero', a.isnumeric())
print('É alfabético ', a.isalpha())
print('É alfnúmerica ', a.isalnum())
print('Esta em maiuscula ', a.isupper())
print('Está em minuscula ', a.islower())
print('Está capitalizada ', a.istitle())